server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.101:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true

jwt:
  config:
    key: tensquare
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
